import * as fs from 'fs';
import * as path from 'path';

const root = path.resolve(__dirname, '..');
const runId = 'run-' + Math.random().toString(36).slice(2, 9);
const runDir = path.resolve(root, `.forge/runs/${runId}`);
const archiveDir = path.resolve(root, '.forge/archive');

// Ensure directories
fs.mkdirSync(runDir, { recursive: true });
fs.mkdirSync(archiveDir, { recursive: true });

interface Event {
  id: string;
  runId: string;
  type: string;
  source: string;
  target?: string;
  status: 'queued' | 'active' | 'passed' | 'failed' | 'complete';
  message: string;
  timestamp: string;
}

const events: Event[] = [];

function emit(type: string, source: string, target: string | undefined, status: any, message: string) {
  const event: Event = {
    id: 'evt-' + Math.random().toString(36).slice(2, 9),
    runId,
    type,
    source,
    target,
    status,
    message,
    timestamp: new Date().toISOString()
  };
  events.push(event);
}

async function run() {
  console.log('🔥 Forge run started\n');
  console.log('Blueprint: Create repository TODO.md\n');

  emit('blueprint.created', 'ForgeEngine', 'Blueprint', 'complete', 'Blueprint task created.');
  
  // 1. Workshop created
  emit('workshop.created', 'ForgeEngine', 'Workshop', 'complete', 'Workshop context initialized.');
  console.log('✓ Workshop created');

  // 2. PlannerArtisan inspects repository
  emit('artisan.started', 'PlannerArtisan', 'Repository', 'active', 'PlannerArtisan inspecting repository structure...');
  fs.readdirSync(root);
  emit('workpiece.created', 'PlannerArtisan', 'Workpiece', 'complete', 'PlannerArtisan created workpiece targets.');
  console.log('✓ PlannerArtisan inspected repository');
  console.log('✓ Workpieces created');

  // 3. BuilderArtisan creates TODO.md
  emit('artisan.started', 'BuilderArtisan', 'TODO.md', 'active', 'BuilderArtisan writing TODO.md...');
  const todoContent = `# Project TODO

## Immediate
- [ ] Implement production-grade orchestrator logic in @forge/engine
- [ ] Connect live WebSockets to forge-dashboard

## Next
- [ ] Support dynamic multi-agent guild clustering
- [ ] Add CLI workflow templates to forge-cli

## Later
- [ ] Implement cloud assayer clustering

## Architecture Notes
- Strict layer separations enforced: Arsenal packages must never import Forge domain packages.

## Generated By
Forge POC run: ${runId}
`;
  fs.writeFileSync(path.resolve(root, 'TODO.md'), todoContent);
  emit('instrument.used', 'BuilderArtisan', 'FilesystemGateway', 'complete', 'Wrote TODO.md to repository root.');
  console.log('✓ BuilderArtisan wrote TODO.md');

  // 4. ReviewerArtisan checks TODO.md sections
  emit('artisan.started', 'ReviewerArtisan', 'TODO.md', 'active', 'ReviewerArtisan checking TODO.md sections...');
  const verifyContent = fs.readFileSync(path.resolve(root, 'TODO.md'), 'utf-8');
  const required = ['# Project TODO', '## Immediate', '## Next', '## Later', '## Architecture Notes', '## Generated By'];
  const missing = required.filter(sec => !verifyContent.includes(sec));

  if (missing.length === 0) {
    emit('inspection.passed', 'ReviewerArtisan', 'TODO.md', 'complete', 'TODO.md verified successfully.');
    console.log('✓ ReviewerArtisan verified TODO.md');
  } else {
    emit('inspection.failed', 'ReviewerArtisan', 'TODO.md', 'failed', `Missing sections: ${missing.join(', ')}`);
    console.log('✗ ReviewerArtisan failed verification');
    throw new Error('TODO.md verification failed');
  }

  // 5. DocumenterArtisan writes run summary
  emit('artisan.started', 'DocumenterArtisan', 'summary.md', 'active', 'DocumenterArtisan compiling summary.md...');
  const summaryContent = `# Forge POC Run Summary

- **Run ID**: ${runId}
- **Status**: Complete
- **Generated File**: TODO.md
- **Timestamp**: ${new Date().toLocaleString()}
`;
  fs.writeFileSync(path.resolve(runDir, 'summary.md'), summaryContent);
  emit('artifact.created', 'DocumenterArtisan', 'summary.md', 'complete', 'summary.md written to run directory.');
  console.log('✓ DocumenterArtisan wrote summary');
  console.log('✓ Artifact created');

  // 6. Archive updated
  emit('archive.updated', 'ForgeEngine', 'latest.json', 'complete', 'Latest run snapshot updated.');
  const latestSnapshot = {
    id: runId,
    timestamp: new Date().toISOString(),
    status: 'complete',
    blueprint: { title: 'Create repository TODO.md' }
  };
  fs.writeFileSync(path.resolve(archiveDir, 'latest.json'), JSON.stringify(latestSnapshot, null, 2));
  console.log('✓ Archive updated');

  // 7. Chronicle updated
  emit('chronicle.updated', 'ForgeEngine', 'chronicle.md', 'complete', 'Chronicle updated.');
  const chronicleEntry = `\n## Forge POC Run - ${runId}\n- **Status**: Success\n- **Date**: ${new Date().toLocaleString()}\n`;
  fs.appendFileSync(path.resolve(root, '.forge/chronicle.md'), chronicleEntry);
  console.log('✓ Chronicle updated');

  // Complete
  emit('forge.completed', 'ForgeEngine', undefined, 'complete', 'Forge run successfully completed.');
  fs.writeFileSync(path.resolve(runDir, 'events.json'), JSON.stringify(events, null, 2));

  console.log('\n✅ Forge run completed');
}

run().catch((err) => {
  console.error('\n❌ Forge run failed:', err);
  process.exit(1);
});
